/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

public class App {
    public String getGreeting() {

    }

    public static void main(String[] args) {

    }
}
